spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    password: password
    username: admin
  liquibase:
    change-log: "classpath:db/changelog/db.changelog-master.yaml"
    enabled: true
